import type { Evento } from './types';

export const SEMESTRE_LABELS: Record<string, string> = {
    "AD25": "Agosto – Diciembre 2025",
    "FJ26": "Febrero – Junio 2026",
};

export const eventos: Evento[] = [
    {
        id: 1,
        titulo: "Bloomberg at Tec",
        fecha: "2025-08-27",
        fechaFin: "2025-08-29",
        tipo: "conferencia",
        estado: "pasado",
        semestre: "AD25",
        descripcion: "Una conferencia que ofrece a los estudiantes una experiencia directa con la empresa Bloomberg, mediante una charla interactiva. El evento incluye un espacio de networking donde los asistentes podrán conocer de primera mano las tecnologías que utiliza Bloomberg, las oportunidades laborales disponibles y el perfil profesional que buscan.",
        ubicacion: "Aulas 2, Auditorio de Biblioteca",
        linkRegistro: "",
    },
    {
        id: 2,
        titulo: "Forjando Caminos: Mujeres en Ingenieria",
        fecha: "2025-09-02",
        tipo: "panel",
        estado: "pasado",
        semestre: "AD25",
        descripcion: "El panel \u201cForjando Caminos: Mujeres en Ingeniería\u201d busca visibilizar y celebrar el papel de las mujeres en el ámbito de la ingeniería. A través de un espacio de diálogo y reflexión, ingenieras compartirán sus experiencias, retos y logros, inspirando a las nuevas generaciones a seguir construyendo un futuro más inclusivo e innovador.",
        ubicacion: "Auditorio de Aulas 6 (A6 – 306)",
        hora: "4:00 pm - 6:00 pm",
        linkRegistro: "",
    },
    {
        id: 3,
        titulo: "Datadog",
        fecha: "2025-09-04",
        tipo: "Recruitment",
        estado: "pasado",
        semestre: "AD25",
        descripcion: {
            texto: "Este evento virtual exclusivo, organizado por Datadog en colaboración con el Tecnológico de Monterrey, está dirigido a estudiantes de Ciencias Computacionales e Ingeniería en Tecnologías Computacionales interesados en iniciar su carrera en Nueva York.",
            bullets: [
                "Conocer el programa de prácticas profesionales de Datadog y vacantes de tiempo completo para Software Engineer.",
                "Escuchar a ingenieros que comenzaron su carrera en Datadog como interns o early hires.",
                "Obtener consejos para destacar en entrevistas y entender mejor la cultura de ingeniería de la empresa.",
            ],
        },
        ubicacion: "En línea vía Zoom",
        linkRegistro: "",
    },
    {
        id: 4,
        titulo: "ITC Talks @ Uber",
        fecha: "2025-09-19",
        tipo: "charla",
        estado: "pasado",
        semestre: "AD25",
        descripcion: "Una charla con David Celis Martínez, exalumno de Ingeniería en Tecnologías Computacionales y referente en la comunidad tech. Ganador del Swift Student Challenge 2023 de Apple, con dos internships en Uber en el área de ingeniería, y actualmente Software Engineer en Uber en San Francisco. David compartirá cómo fue su camino desde el ITC hasta Silicon Valley.",
        ubicacion: "En Linea, Via Zoom",
        linkRegistro: "",
    },
    {
        id: 5,
        titulo: "CV Power Up",
        fecha: "2025-09-25",
        tipo: "taller",
        estado: "pasado",
        semestre: "AD25",
        descripcion: "Un taller para optimizar el currículum de estudiantes de Ingeniería en Tecnologías Computacionales, con enfoque en la industria tech y de software, logrando al menos 25 asistentes activos durante una sesión de 2 horas, y brindando retroalimentación personalizada a los participantes que traigan su CV.",
        ubicacion: "Aula de Conferencias",
        linkRegistro: "",
    },
    {
        id: 6,
        titulo: "Ingeniería con Conciencia",
        fecha: "2025-10-02",
        tipo: "panel",
        estado: "pasado",
        semestre: "AD25",
        descripcion: "Un evento tipo panel dirigido a estudiantes ITC y de la avenida ICT, el cual tiene como propósito discutir la relevancia de la ética profesional y tecnológica en la industria. A través de casos reales y experiencias compartidas por expertos, se busca generar un diálogo de alto impacto sobre cómo las decisiones que se toman pueden tener un efecto significativo en nuestro entorno.",
        ubicacion: "Sala Novela, Piso 6 - Biblioteca",
        linkRegistro: "",
    },
    {
        id: 7,
        titulo: "Prep2Intern",
        fecha: "2025-12-10",
        tipo: "conferencia",
        estado: "proximo",
        semestre: "AD25",
        descripcion: "Una conferencia donde estudiantes de ITC que han conseguido internships en empresas reconocidas (nacionales o internacionales), a través de un panel conversacional, con el objetivo de inspirar y orientar a por lo menos 30 estudiantes en su camino hacia prácticas profesionales o internships en la industria tecnológica.",
        ubicacion: "Auditorio de Aulas 6",
        linkRegistro: "",
    },
    {
        id: 8,
        titulo: "SEITC Challenge",
        fecha: "2026-04-10",
        tipo: "competencia",
        estado: "proximo",
        semestre: "FJ26",
        descripcion: "Un hackatón dirigido a estudiantes de Ingeniería, con el objetivo de fomentar la creatividad, la solución de problemas reales y el trabajo en equipo.",
        ubicacion: "Laboratorios de Innovación",
    },
    {
        id: 9,
        titulo: "Congreso SEITC",
        fecha: "2026-04-09",
        tipo: "conferencia",
        estado: "proximo",
        semestre: "FJ26",
        descripcion: "Congreso organizado por SEITC, más detalles próximamente.",
        ubicacion: "Próximamente",
    },
];
