name: Sync To Deploy Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to deploy repository
        uses: actions/checkout@v4
        with:
          repository: seitcMty/seitc-webpage
          token: ${{ secrets.DEPLOY }}
          path: deploy

      - name: Sync files
        run: |
          rsync -av --delete --exclude '.git' ./ deploy/
          cd deploy
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Sync from SEITC-MTY" || echo "No changes to commit"
          git push origin main
          
# name: Sync Forked Repo

# on:
#   push:
#     branches:
#       - main   

# env:
#   TARGET_ACCOUNT: seitcMty

# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Update Fork
#         run: |
#           REPO_NAME=${GITHUB_REPOSITORY##*/}
#           ACCOUNT=${{env.TARGET_ACCOUNT}}
#           curl -L \
#           -X POST \
#           -H "Accept: application/vnd.github+json" \
#           -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
#           -H "X-GitHub-Api-Version: 2022-11-28" \
#           https://api.github.com/repos/$ACCOUNT/$REPO_NAME/merge-upstream \
#           -d '{"branch": "main"}'
